jobs:
  deploy:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion ==
      'success' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up WARP
      uses: fscarmen/warp-on-actions@v1.1
      with:
        stack: dual
    - continue-on-error: true
      name: SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PLAYGROUND_SSH_HOST }}
        key: ${{ secrets.PLAYGROUND_SSH_KEY }}
        protocol: tcp6
        script: 'cd /opt/turms

          sudo docker compose -f docker-compose.standalone.yml down --remove-orphans

          sudo docker system prune -a -f

          sudo docker system prune --volumes -f

          sudo rm -rf /var/log/journal

          sudo git reset --hard

          sudo git pull

          sudo ENV=dev,demo INITIAL_ROOT_PASSWORD=''${{ secrets.PLAYGROUND_ROOT_PASSWORD
          }}'' docker compose -f docker-compose.standalone.yml --profile monitoring
          up --force-recreate -d'
        script_stop: true
        username: ${{ secrets.PLAYGROUND_SSH_USERNAME }}
name: Deploy Playground
on:
  repository_dispatch:
    types: trigger-ga___deploy-playground.yml
