jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      id: qemu
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - continue-on-error: true
      id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - continue-on-error: true
      name: Build turms-service image
      run: DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64
        --rm=false -t "ghcr.io/turms-im/turms-service:latest" -f turms-service/Dockerfile
        .
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      name: Docker login
      run: docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
    - continue-on-error: true
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      name: Publish turms-service (Use cache)
      run: DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64
        --tag "ghcr.io/turms-im/turms-service:latest" --push -f turms-service/Dockerfile
        .
name: Publish turms-service
on:
  repository_dispatch:
    types: trigger-ga___publish-turms-service.yml
