jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build
      run: 'mvn clean package -Dmaven.test.skip=true -am -B -pl \

        turms-plugins/turms-plugin-antispam,\

        turms-plugins/turms-plugin-minio,\

        turms-plugins/turms-plugin-push,\

        turms-plugins/turms-plugin-rasa \

        --no-transfer-progress

        '
    - continue-on-error: true
      name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: turms-plugins/**/target/*.jar
        generate_release_notes: false
        name: v0.10.0-SNAPSHOT
        prerelease: true
        tag_name: v0.10.0-SNAPSHOT
name: Publish turms plugins
on:
  repository_dispatch:
    types: trigger-ga___publish-turms-plugins.yml
