jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Maven Verify
      run: 'mvn clean install -Dmaven.test.skip=true -am -B -pl turms-plugins/turms-plugin-rasa
        --no-transfer-progress

        mvn verify -pl turms-plugins/turms-plugin-rasa'
name: Test turms-plugin-rasa
on:
  repository_dispatch:
    types: trigger-ga___test-turms-plugin-rasa.yml
