jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Build
      run: swift build -v
      working-directory: turms-client-swift
name: Test turms-client-swift
on:
  repository_dispatch:
    types: trigger-ga___test-turms-client-swift.yml
