jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Init - Playground
      run: terraform init
      working-directory: ./terraform/alicloud/playground
    - continue-on-error: true
      name: Validate - Playground
      run: terraform validate
      working-directory: ./terraform/alicloud/playground
    - continue-on-error: true
      name: Verify Format - Playground
      run: terraform fmt -diff -check
      working-directory: ./terraform/alicloud/playground
    - continue-on-error: true
      name: Init - Cluster
      run: terraform init
      working-directory: ./terraform/alicloud/cluster
    - continue-on-error: true
      name: Validate - Cluster
      run: terraform validate
      working-directory: ./terraform/alicloud/cluster
    - continue-on-error: true
      name: Verify Format - Cluster
      run: terraform fmt -diff -check
      working-directory: ./terraform/alicloud/cluster
name: Test Terraform
on:
  repository_dispatch:
    types: trigger-ga___test-terraform.yml
