jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up Node
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 20
    - continue-on-error: true
      name: Install dependencies
      run: npm install
      working-directory: turms-client-js
    - continue-on-error: true
      name: Verify formatting
      run: npm run lint
      working-directory: turms-client-js
    - continue-on-error: true
      name: Build artifacts
      run: npm run build
      working-directory: turms-client-js
name: Test turms-client-js
on:
  repository_dispatch:
    types: trigger-ga___test-turms-client-js.yml
