jobs:
  ui-tests:
    container: cypress/browsers:node16.14.0-chrome99-ff97
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Cypress run
      uses: cypress-io/github-action@v6.5.0
      with:
        build: npm run build
        start: npm run serve
        wait-on: http://localhost:6510
        working-directory: turms-admin
name: Test turms-admin
on:
  repository_dispatch:
    types: trigger-ga___test-turms-admin.yml
